FROM python:3.11.0

WORKDIR /Streamlit

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY app.py .
COPY plugins ./plugins 

EXPOSE 8503

CMD ["streamlit", "run", "app.py", "--server.port", "8503"]