FROM apache/airflow:2.8.1

USER root


RUN apt-get update && \
    apt-get install -y --no-install-recommends wget unzip build-essential libsndfile1 libopenmpi-dev && \
    apt-get autoremove -yqq --purge && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


COPY requirements.txt /


USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
            openjdk-17-jre-headless \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


USER airflow
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
RUN pip install --no-cache-dir "apache-airflow==${AIRFLOW_VERSION}" -r /requirements.txt