FROM tiangolo/uvicorn-gunicorn-fastapi:python3.10

WORKDIR /FastAPI2

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
